release:
  enabled: true

docker:
  composeFile:
    - compose.18.yaml
  defaultTag: latest
  autoTags: [main, latest, next]

docs:
  location: /docs

  externalTypes:
    - corejslib/core
    - corejslib/result
