docker:
    composeFile:
        - compose.17.yaml
    defaultTag: latest
    autoTags: [main, latest, next]

docs:
    location: /docs

    externalTypes:
        - softvisio-node/core
        - softvisio-node/result
